import { initializeTestEnvironment, assertSucceeds, assertFails } from "@firebase/rules-unit-testing";
import { doc, setDoc, getDoc, deleteDoc, updateDoc, serverTimestamp, Timestamp, deleteField } from "firebase/firestore";
import fs from "fs";
const env = await initializeTestEnvironment({ projectId: "demo-tag-ledger", firestore: { rules: fs.readFileSync(new URL("../firestore.rules", import.meta.url),"utf8"), host:"127.0.0.1", port:8080 } });
const g = env.authenticatedContext("u1",{email:"group@tagledger.app"}).firestore();
const a = env.authenticatedContext("u2",{email:"admin@tagledger.app"}).firestore();
const x = env.authenticatedContext("u3",{email:"random@x.com"}).firestore();
const anon = env.unauthenticatedContext().firestore();
const today = new Date().toISOString().slice(0,10);
const base = d => ({date:d, t:Date.now(), team1:["Chottu","Hari"], team2:["Sanjai","Karthik S"], winner:1, counted:true});
const hrs = h => Timestamp.fromMillis(Date.now()-h*3600e3);
await env.withSecurityRulesDisabled(async c=>{
  const f=c.firestore();
  await setDoc(doc(f,"matches","old"),{...base("2026-10-05"),createdAt:hrs(2)});
  await setDoc(doc(f,"matches","fresh"),{...base(today),createdAt:hrs(0.25)});
});
const r=[]; const t=async(n,p)=>{ try{ await p; r.push("PASS "+n);}catch(e){ r.push("FAIL "+n+" "+e.message);} };
await t("group creates today's match", assertSucceeds(setDoc(doc(g,"matches","n1"),{...base(today),createdAt:serverTimestamp()})));
await t("group can't backdate a match", assertFails(setDoc(doc(g,"matches","n2"),{...base("2026-09-01"),createdAt:serverTimestamp()})));
await t("group can't fake createdAt", assertFails(setDoc(doc(g,"matches","n3"),{...base(today),createdAt:hrs(2)})));
await t("group can't edit a score", assertFails(updateDoc(doc(g,"matches","fresh"),{winner:2})));
await t("group can't overwrite via set", assertFails(setDoc(doc(g,"matches","fresh"),{...base(today),winner:2,createdAt:serverTimestamp()})));
await t("group deletes match <1h old", assertSucceeds(deleteDoc(doc(g,"matches","fresh"))));
await t("group can't delete match >1h old", assertFails(deleteDoc(doc(g,"matches","old"))));
await t("admin can't delete match >1h old", assertFails(deleteDoc(doc(a,"matches","old"))));
await t("admin can't edit", assertFails(updateDoc(doc(a,"matches","old"),{winner:2})));
await t("admin restores missing old match", assertSucceeds(setDoc(doc(a,"matches","r1"),{...base("2026-10-06"),createdAt:hrs(2)})));
await t("admin restore can't overwrite existing", assertFails(setDoc(doc(a,"matches","old"),{...base("2026-10-05"),winner:2,createdAt:hrs(3)})));
await t("group reads", assertSucceeds(getDoc(doc(g,"matches","old"))));
await t("stranger can't read", assertFails(getDoc(doc(x,"matches","old"))));
await t("signed-out can't read", assertFails(getDoc(doc(anon,"matches","old"))));
await t("stranger can't write", assertFails(setDoc(doc(x,"matches","n4"),{...base(today),createdAt:serverTimestamp()})));
await t("bad shape rejected", assertFails(setDoc(doc(g,"matches","n5"),{...base(today),winner:3,createdAt:serverTimestamp()})));
await t("group logs match with wrestlers", assertSucceeds(setDoc(doc(g,"matches","n6"),{...base(today),wrestlers1:["Roman Reigns",""],wrestlers2:["John Cena","The Rock"],createdAt:serverTimestamp()})));
await t("wrestlers must be a pair", assertFails(setDoc(doc(g,"matches","n7"),{...base(today),wrestlers1:["Roman Reigns"],createdAt:serverTimestamp()})));
await t("group adds a player", assertSucceeds(setDoc(doc(g,"players","hari"),{name:"Hari",createdAt:serverTimestamp()})));
await t("player id must match name", assertFails(setDoc(doc(g,"players","someone"),{name:"Hari2",createdAt:serverTimestamp()})));
await t("no duplicate player", assertFails(setDoc(doc(g,"players","hari"),{name:"HARI",createdAt:serverTimestamp()})));
await t("group can't delete a player", assertFails(deleteDoc(doc(g,"players","hari"))));
await t("admin deletes a player", assertSucceeds(deleteDoc(doc(a,"players","hari"))));
await t("group adds a team", assertSucceeds(setDoc(doc(g,"teams","chottu+hari"),{players:["Chottu","Hari"],nick:"",createdAt:serverTimestamp()})));
await t("team id must match players", assertFails(setDoc(doc(g,"teams","x+y"),{players:["Chottu","Sai"],nick:"",createdAt:serverTimestamp()})));
await t("team players must be in order", assertFails(setDoc(doc(g,"teams","sai+chottu"),{players:["Sai","Chottu"],nick:"",createdAt:serverTimestamp()})));
await t("group sets team nickname", assertSucceeds(updateDoc(doc(g,"teams","chottu+hari"),{nick:"The Bloodline"})));
await t("can't change team players", assertFails(updateDoc(doc(g,"teams","chottu+hari"),{players:["Chottu","Sai"]})));
await t("stranger can't add a player", assertFails(setDoc(doc(x,"players","zed"),{name:"Zed",createdAt:serverTimestamp()})));
await t("group edits player alias", assertSucceeds(setDoc(doc(g,"players","sai"),{name:"Sai",createdAt:serverTimestamp()}).then(()=>updateDoc(doc(g,"players","sai"),{alias:"The Viper"}))));
await t("group deletes (hides) a player", assertSucceeds(updateDoc(doc(g,"players","sai"),{hidden:true})));
await t("can't rename a player", assertFails(updateDoc(doc(g,"players","sai"),{name:"Saii"})));
await t("stranger can't edit a player", assertFails(updateDoc(doc(x,"players","sai"),{alias:"x"})));
await t("group flags a locked result", assertSucceeds(updateDoc(doc(g,"matches","old"),{flag:{reason:"Wrong winner",at:serverTimestamp()}})));
await t("flag can't be overwritten", assertFails(updateDoc(doc(g,"matches","old"),{flag:{reason:"again",at:serverTimestamp()}})));
await t("flag can't sneak in a score change", assertFails(updateDoc(doc(g,"matches","r1"),{flag:{reason:"x",at:serverTimestamp()},winner:2})));
await t("empty flag reason rejected", assertFails(updateDoc(doc(g,"matches","r1"),{flag:{reason:"",at:serverTimestamp()}})));
await t("group can't void", assertFails(updateDoc(doc(g,"matches","old"),{voided:true})));
await t("group can't remove a flag", assertFails(updateDoc(doc(g,"matches","old"),{flag:deleteField()})));
await t("stranger can't flag", assertFails(updateDoc(doc(x,"matches","r1"),{flag:{reason:"x",at:serverTimestamp()}})));
await t("admin voids a flagged match", assertSucceeds(updateDoc(doc(a,"matches","old"),{voided:true})));
await t("admin can't change score while voiding", assertFails(updateDoc(doc(a,"matches","old"),{voided:false,winner:2})));
await t("admin dismisses a flag", assertSucceeds(updateDoc(doc(a,"matches","old"),{flag:deleteField()})));
await t("can't flag a voided match", assertFails(updateDoc(doc(g,"matches","old"),{flag:{reason:"x",at:serverTimestamp()}})));
await t("new match can't arrive voided", assertFails(setDoc(doc(g,"matches","n8"),{...base(today),voided:true,createdAt:serverTimestamp()})));
await t("admin adds a result for an old date", assertSucceeds(setDoc(doc(a,"matches","p1"),{...base("2026-09-01"),createdAt:Timestamp.fromMillis(Date.now()-120000)})));
await t("admin can delete it within the hour", assertSucceeds(deleteDoc(doc(a,"matches","p1"))));
await t("group can't add an old date even with a past createdAt", assertFails(setDoc(doc(g,"matches","p2"),{...base("2026-09-01"),createdAt:Timestamp.fromMillis(Date.now()-120000)})));
console.log(r.join("\n")); await env.cleanup(); process.exit(r.some(x=>x.startsWith("FAIL")) ? 1 : 0);
